config/routes.rb
Rails.application.routes.draw do
  root to: 'staticpages#home'
  resources  :mypages,       only: [:show, :index,]
  resources :mypages do
    member do
      get :following, :followers
    end
  end
  devise_for :users, controllers: { registraions:       'users/registraions',
                                    sessions:           'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks'  }
  
  resources  :photoposts,    only: [:show,:create, :destroy] do
    resources :comments, only: [:show, :create, :destroy]
  end
  resources  :relationships, only: [:create, :destroy]
  resources  :likes,         only: [:create, :destroy]
end

app/views/shared/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/shared/_photo_form.html.erb
<h1>画像を投稿する</h1>
<%= form_for(@photopost) do |f| %>
  <span class="picture">
    <%= f.file_field :picture %>
  </span>
  <div class="field">
    <%= f.text_area :content, placeholder: "コメントの追加" %>
  </div>
  <%= f.submit "投稿", class: "btn btn-success" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_mypage_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_mypage_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォロー中", class: "btn" %>
<% end %>