config/routes.rb
Rails.application.routes.draw do
  root to: 'staticpages#home'
  resources  :mypages,       only: [:show, :index,]
  resources :mypages do
    member do
      get :following, :followers
    end
  end
  devise_for :users, controllers: { registraions:       'users/registraions',
                                    sessions:           'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks'  }
  
  resources  :photoposts,    only: [:show,:create, :destroy] do
    resources :comments, only: [:show, :create, :destroy]
  end
  resources  :relationships, only: [:create, :destroy]
  resources  :likes,         only: [:create, :destroy]
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!, only: [:following, :followers]

   def index
    @users = User.all.search(params[:search])
   end

   def show
     @user = User.find(params[:id])
     @photoposts = @user.photoposts.search(params[:search])
   end
   
   def following
     @title = "フォロー"
     @user  = User.find(params[:id])
     @users = @user.following
     render 'show_follow'
   end
   
   def followers
     @title = "フォロワー"
     @user  = User.find(params[:id])
     @users = @user.followers
     render 'show_follow'
   end
end

app/helpers/mypages_helper.rb
module MypagesHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/mypages/WIP_comment_form.html.erb
<%= form_with model [@photopost, @comment], local: true do |f| %>
   <%= render 'shared/error_messages', object: f.object %>
   
   <div class='form-group'>
     <%= f.text_area :content, class: 'form-control', id: 'content'\
                      placeholder: "コメントを入力してください" %>
   </div>
   
   <%= f.submit "コメントする", class: "btn btn-primary" %>
<% end %>

app/views/mypages/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'shared/unfollow' %>
  <% else %>
    <%= render 'shared/follow' %>
  <% end %>
  </div>
<% end %>

app/views/mypages/index.html.erb
<h1>フォローする?</h1>
<!--検索機能-->
<p>ユーザー検索</p>
<%= form_tag(mypages_path, :method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag '検索', :name => nil %>
<% end %>


<ul class="users">
  <%= render @users %>
</ul>

app/views/mypages/show.html.erb
<h1><%= @user.name%></h1>
<div><%= link_to 'プロフィールの編集', edit_user_registration_path %></div>
<aside class="col-md-4">
  <h1>
    <%= gravatar_for @user %>
    <%= render 'follow_form' if user_signed_in? %>
  </h1>
  <section class="stats">
    <%= render 'shared/stats' %>
  </section>
</aside>
<!--検索拡張機能-->
  <%= form_tag mypage_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "検索", :name => nil %>
    </p>
  <% end %>
<div class="col-md-8">
<h3><%= @user.photoposts.count %>投稿</h3>
  <ol class="photoposts">
     <%= render @photoposts %>
     <!--< @comments.each do |comment| %>-->
     <!--  <= comment.user.name %>-->
     <!--  <= comment.content %>-->
     <!--  <= link_to "削除する", photopost_comment_path(@photopost, comment), method: :delete %>-->
     <!--< end %>-->
     <!--<= render 'comment_form' %>-->
  </ol>
</div>

app/views/mypages/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "プロフィール", mypage_path(@user) %></span>
      <span><b>画像投稿</b><%= @user.photoposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
      <div class="avatars">
        <% @users.each do |user| %>
          <%= link_to gravatar_for(user, size:30), mypage_path(user) %>
        <% end %>
      </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <% @users.each do |user| %>
          <li>
            <%= gravatar_for(user, size:50) %>
            <%= link_to user.name, mypage_path(user) %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>